---
- name: Deploy ansistrano.com to ansistrano.com server
  hosts: all
  vars:
    ansistrano_deploy_from: "./"
    ansistrano_deploy_to: "/www/ansistrano.com"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/deploy/tasks/after-symlink.yml"
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
